repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: python -m flake8
        types: [python]
        exclude: setup.py
    -   id: isort
        name: isort
        stages: [commit]
        language: system
        entry: python -m isort .
        types: [python]
    -   id: black
        name: black
        stages: [commit]
        language: system
        entry: python -m black .
        types: [python]
    -   id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: python -m mypy
        types: [python]
